# Generated by Django 5.1.3 on 2024-12-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Adminreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adminreg_name', models.CharField(max_length=50)),
                ('Adminreg_Email', models.CharField(max_length=50)),
                ('Adminreg_password', models.CharField(max_length=50)),
            ],
        ),
    ]
