# Generated by Django 5.1.3 on 2024-12-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.CharField(max_length=50)),
                ('event_count', models.CharField(max_length=50)),
                ('event_todate', models.CharField(max_length=50)),
                ('event_status', models.IntegerField(default=0)),
                ('event_price', models.CharField(max_length=50)),
            ],
        ),
    ]
