# Generated by Django 5.1.4 on 2025-03-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0007_initial'),
        ('User', '0029_delete_tbl_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_artwork',
        ),
    ]
