# Generated by Django 5.1.4 on 2025-03-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0010_tbl_event'),
        ('Artist', '0008_delete_tbl_artwork'),
        ('Guest', '0004_tbl_artist_artist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_photo', models.FileField(upload_to='Assets/User/Photo/')),
                ('artwork_status', models.IntegerField(default=0)),
                ('artwork_price', models.CharField(max_length=30)),
                ('artwork_name', models.CharField(max_length=30)),
                ('artwork_description', models.CharField(max_length=50)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
            ],
        ),
    ]
