# Generated by Django 5.1.7 on 2025-04-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_auctionhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionhead_amount', models.CharField(max_length=30)),
                ('auctionhead_date', models.DateField(auto_now_add=True)),
                ('auctionhead_todate', models.DateField()),
                ('auction_starttime', models.CharField(max_length=30)),
                ('auctionhead_status', models.IntegerField(default=0)),
                ('auction_totalamount', models.CharField(max_length=30)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artist.tbl_artwork')),
            ],
        ),
    ]
