# Generated by Django 5.1.7 on 2025-04-11 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0010_tbl_auctionhead'),
        ('Guest', '0005_tbl_deliveryboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_auctionhead',
            name='deliveryboy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_deliveryboy'),
        ),
    ]
