# Generated by Django 5.1.7 on 2025-04-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0011_tbl_auctionhead_deliveryboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_auctionhead',
            name='deliveryboy_status',
            field=models.IntegerField(default=0),
        ),
    ]
