# Generated by Django 5.1.3 on 2024-12-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_product'),
        ('Guest', '0002_tbl_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=30)),
                ('artist_email', models.CharField(max_length=30)),
                ('artist_contact', models.CharField(max_length=30)),
                ('artist_address', models.CharField(max_length=50)),
                ('artist_photo', models.FileField(upload_to='Assets/User/Photo/')),
                ('artist_proof', models.FileField(upload_to='Assets/User/Photo/')),
                ('artist_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
