# Generated by Django 5.1.4 on 2025-03-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_event'),
        ('Guest', '0004_tbl_artist_artist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deliveryboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryboy_name', models.CharField(max_length=30)),
                ('deliveryboy_email', models.CharField(max_length=30)),
                ('deliveryboy_contact', models.CharField(max_length=30)),
                ('deliveryboy_address', models.CharField(max_length=50)),
                ('deliveryboy_photo', models.FileField(upload_to='Assets/User/Photo/')),
                ('deliveryboy_proof', models.FileField(upload_to='Assets/User/Photo/')),
                ('deliveryboy_password', models.CharField(max_length=30)),
                ('deliveryboy_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
