# Generated by Django 5.1.3 on 2024-12-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='booking_status',
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_date',
            field=models.IntegerField(default=0),
        ),
    ]
