# Generated by Django 5.1.3 on 2024-12-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_tbl_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
    ]
