# Generated by Django 5.1.3 on 2024-12-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_eventbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_eventbooking',
        ),
    ]
