# Generated by Django 5.1.3 on 2024-12-20 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_event'),
        ('Guest', '0004_tbl_artist_artist_status'),
        ('User', '0006_delete_tbl_eventbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_eventbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventbooking_date', models.DateField(auto_now_add=True)),
                ('eventbooking_count', models.CharField(max_length=50)),
                ('eventbooking_price', models.CharField(max_length=50)),
                ('eventbooking_status', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
