# Generated by Django 5.1.4 on 2025-01-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_tbl_ticket_booking_tbl_tickets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
    ]
