# Generated by Django 5.1.4 on 2025-01-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_tbl_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
    ]
