# Generated by Django 5.1.4 on 2025-01-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_tbl_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
