# Generated by Django 5.1.4 on 2025-01-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_tbl_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_chat',
        ),
    ]
