# Generated by Django 5.1.4 on 2025-01-26 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_artist_artist_status'),
        ('User', '0025_tbl_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_chat',
            name='artist_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_from', to='Guest.tbl_artist'),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='artist_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_to', to='Guest.tbl_artist'),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='user_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user'),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user'),
        ),
    ]
