# Generated by Django 5.1.4 on 2025-02-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_alter_tbl_chat_artist_from_alter_tbl_chat_artist_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_tickets',
            name='booking',
        ),
        migrations.DeleteModel(
            name='tbl_ticket_booking',
        ),
        migrations.DeleteModel(
            name='tbl_tickets',
        ),
    ]
