# Generated by Django 5.1.4 on 2025-03-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_tbl_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
