# Generated by Django 5.1.7 on 2025-03-30 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_deliveryboy'),
        ('User', '0032_tbl_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='deliveryboy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_deliveryboy'),
        ),
    ]
